name 'jdjenkins'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures jdjenkins'
long_description 'Installs/Configures jdjenkins'
version '0.1.0'
depends 'jenkins'